version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
  web:
    build: .
    command: go run main.go
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db