name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create dotenv
        run: echo > .env
      - name: Compile
        run: go build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: latest
          path: main.go
